import '../styles/globals.css';
import { cn } from '@/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Cinema Shift 2024',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'mx-auto max-w-[960px]')}>{children}</body>
    </html>
  );
};

export default RootLayout;
