import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Cinema Shift 2024',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  // const viewport = cookies().get('viewport')?.value;

  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
